services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./chat-front/envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"